--
-- SECUENCIA: VIDEOJUEGOS
--
CREATE SEQUENCE VIDEOJUEGOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

--
-- SECUENCIA: PELICULAS
--
CREATE SEQUENCE PELICULAS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: PRODUCTOS
--
CREATE SEQUENCE PRODUCTOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: VIA_STREAMING
--
CREATE SEQUENCE VIA_STREAMING_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: MODALIDAD_ENVIO
--
CREATE SEQUENCE MODALIDAD_ENVIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: VIA_PAQUETERIA
--
CREATE SEQUENCE VIA_PAQUETERIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: ESCALA
--
CREATE SEQUENCE ESCALA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: EMPRESA PAQUETERIA
--
CREATE SEQUENCE EMPRESA PAQUETERIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: CLIENTE
--
CREATE SEQUENCE CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: ORDEN_COMPRA
--
CREATE SEQUENCE ORDEN_COMPRA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- SECUENCIA: FACTURA
--
CREATE SEQUENCE FACTURA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

--
-- SECUENCIA: FORMA_PAGO
--
CREATE SEQUENCE FORMA_PAGO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

--
-- SECUENCIA: ALBUM_MUSICAL
--
CREATE SEQUENCE ALBUM_MUSICAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;


--
-- TABLA: FACTURA
-- FACTURA_ID: CLAVE DE LA FACTURA
--
CREATE TABLE FACTURA(
    FACTURA_ID  NUMBER(5, 0) NOT NULL UNIQUE,
    IVA NUMBER(7,2) NOT NULL,
    MONTO NUMBER(8,2) NOT NULL,
    CONSTRAINT FACTURA_ID_PK PRIMARY KEY (FACTURA_ID)
)
;

--
-- TABLA: FACTURA DE PAGO
-- OVERLAPPING CON TARJET DE CREDITO Y TRANSFERENCIA BANCARIA
--REVISAR
CREATE TABLE FORMA_PAGO(
    FORMA_PAGO_ID  NUMBER(5, 0) NOT NULL,
    TITULAR VARCHAR2(20) NOT NULL,
    NOMBRE_BANCO VARCHAR2(15) NOT NULL,
    FACTURA_ID NUMBER(5, 0) NOT NULL,
    TARJETA_CREDITO_ID NUMBER(16,0) NULL,
    TRANSFERENCIA_BANCARIA_ID NUMBER(16,0) NULL,
    CONSTRAINT TRANSFERENCIA_BANCARIA_ID_FK FOREIGN KEY (TRANSFERENCIA_BANCARIA_ID),
    CONSTRAINT FACTURA_ID_FK FOREIGN KEY (FACTURA_ID),
    CONSTRAINT TARJETA_CREDITO_ID_FK FOREIGN KEY (TARJETA_CREDITO_ID),
    CONSTRAINT TARJETA_CREDITO_ID_FK FOREIGN KEY (TARJETA_CREDITO_ID),
    CONSTRAINT FORMA_PAGO_PK PRIMARY KEY (FORMA_PAGO_ID)
)
;

--
-- TABLA: TARJETA
-- TARJETA_CREDITO_ID: NUMERO DE TARJETA
--
CREATE TABLE TARJETA_CREDITO(
    TARJETA_CREDITO_ID NUMBER(16, 0) NOT NULL,
    NUMERO_SEGURIDAD VARCHAR2(20) NOT NULL,
    ANO_VENCIMIENTO NUMBER(4,0) NOT NULL,
    MES_VENCIMIENTO NUMBER(2,0) NOT NULL,
    TIPO_TARJETA VARCHAR2(14,0) NOT NULL,
    CONSTRAINT TARJETA_CREDITO_ID_UQ UNIQUE (FORMA_PAGO_ID),
    CONSTRAINT TARJETA_CREDITO_ID_PK PRIMARY KEY (FORMA_PAGO_ID),
    CONSTRAINT TIPO_TARJETA_CHECK
    CHECK (TIPO_TARJETA='MASTER CARD' OR TIPO_TARJETA='AMERICAN EXPRESS' OR TIPO_TARJETA='VISA'),
)
;

--
-- TABLA: TRANSFERENCIA BANCARIA
-- TRANSFERENCIA_BANCARIA_ID: CLAVE INTERBANCARIA
--
CREATE TABLE TRANSFERENCIA_BANCARIA(
    TRANSFERENCIA_BANCARIA_ID VARCHAR2(40) NOT NULL,
    CONSTRAINT TRANSFERENCIA_BANCARIA_ID_UQ UNIQUE (TRANSFERENCIA_BANCARIA_ID),
    CONSTRAINT TRANSFERENCIA_BANCARIA_ID_PK PRIMARY KEY (TRANSFERENCIA_BANCARIA_ID),
)
;

--
-- TABLA: VIA_PAQUETERIA
--
CREATE TABLE VIA_PAQUETERIA(
    VIA_PAQUETERIA_ID NUMBER(5,0) NOT NULL,
    ENTIDAD_FEDERATIVA VARCHAR2(20) NOT NULL,
    MUNICIPIO VARCHAR2(20) NOT NULL,
    CALLE VARCHAR2(20) NOT NULL,
    NUM_INTERIOR NUMBER(4,0) NOT NULL,
    NUM_EXTERIOR NUMBER(4,0) NULL DEFAULT NULL,
    COLONIA VARCHAR2(20) NOT NULL,
    CODIGO_POSTAL NUMBER(6) NOT NULL,
    CONSTRAINT VIA_PAQUETERIA_ID_PK PRIMARY KEY (TRANSFERENCIA_BANCARIA_ID),
    CONSTRAINT CODIGO_POSTAL_CH UNIQUE (CODIGO_POSTAL)
)
;

--
-- TABLA: PAQUETE
--
CREATE TABLE PAQUETE(
    PAQUETE_ID NUMBER(5,0) NOT NULL,
    VIA_PAQUETERIA_ID NUMBER(5,0) NOT NULL,
    FACTURA_ID NUMBER(5,0) NOT NULL,
    CONSTRAINT PAQUETE_ID_PK PRIMARY KEY (PAQUETE_ID),
    CONSTRAINT FACTURA_ID_FK FOREIGN KEY (FACTURA_ID),
    CONSTRAINT VIA_PAQUETERIA_ID FOREIGN KEY (VIA_PAQUETERIA_ID)
)
;

--
-- TABLA: EMPRESA PAQUETERIA
--
CREATE TABLE EMPRESA_PAQUETERIA(
    EMPRESA_PAQUETERIA_ID NUMBER(5,0) NOT NULL,
    ZONA VARCHAR2(1) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    PAQUETE_ID NUMBER(5,0) NOT NULL,
    CONSTRAINT EMPRESA_PAQUETERIA_ID_PK PRIMARY KEY (EMPRESA_PAQUETERIA_ID),
    CONSTRAINT PAQUETE_ID_FK FOREIGN KEY (PAQUETE_ID),
    CONSTRAINT ZONA_CH CHECK (ZONA='A' OR ZONA='B' OR ZONA='C'),
    CONSTRAINT ZONA_UQ UNIQUE (NOMBRE)
)
;
--
-- FALTA ESCALA
--
--

--
-- TABLA: ORDEN COMPRA
-- ORDEN_COMPRA_ID: FOLIO
--
CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID VARCHAR2(10) NOT NULL,
    FACTURA_ID NUMBER(5,0) NOT NULL,
    CONSTRAINT ORDEN_COMPRA_ID_UQ UNIQUE (ORDEN_COMPRA_ID),
    CONSTRAINT CLIENTE_ID_PK PRIMARY KEY (ORDEN_COMPRA_ID),
    CONSTRAINT FACTURA_ID_FK FOREIGN KEY (ORDEN_COMPRA_ID)
)
;


--
-- TABLA: CLIENTE
-- CLIENTE_ID: USERNAME
--
CREATE TABLE CLIENTE(
    CLIENTE_ID VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDO VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    RFC VARCHAR2(13) NOT NULL,
    ORDEN_COMPRA_ID VARCHAR2(10) NOT NULL,
    CONSTRAINT CLIENTE_ID_UQ UNIQUE (RFC),
    CONSTRAINT RFC_UQ UNIQUE (CLIENTE_ID),
    CONSTRAINT CLIENTE_ID_PK PRIMARY KEY (FORMA_PAGO_ID),
    CONSTRAINT ORDEN_COMPRA_ID_FK FOREIGN KEY (ORDEN_COMPRA_ID)
)
;


--
-- TABLA: MODALIDAD_ENVIO
--
CREATE TABLE MODALIDAD_ENVIO(
    MODALIDAD_ENVIO_ID VARCHAR2(20) NOT NULL,
    VIA_STREAMING_ID NUMBER(5,0) NOT NULL,
    VIA_PAQUETERIA_ID NUMBER(5,0) NOT NULL,
    ORDEN_COMPRA_ID VARCHAR2(10) NOT NULL,
    CONSTRAINT MODALIDAD_ENVIO_PK PRIMARY KEY (MODALIDAD_ENVIO_ID),
    CONSTRAINT VIA_STREAMING_ID_FK FOREIGN KEY (VIA_STREAMING_ID),
    CONSTRAINT VIA_PAQUETERIA_ID_FK FOREIGN KEY (VIA_PAQUETERIA_ID)
)
;

--
-- TABLA: VIA_STREAMING
--
CREATE TABLE VIA_STREAMING(
    VIA_STREAMING_ID NUMBER(5,0) NOT NULL,
    URL VARCHAR2(30,0) NOT NULL,
    REPETICIONES NUMBER(4) NULL DEFAULT 0,
    CONSTRAINT VIA_STREAMING_ID_PK PRIMARY KEY (VIA_STREAMING_ID)
)
;

--
-- TABLA: PRODUCTOS
--
CREATE TABLE PRODUCTOS(
    PRODUCTOS_ID NUMBER(5,0) NOT NULL,
    PRECIO NUMBER(6,2) NOT NULL,
    PELICULAS_ID NUMBER(5,0) NULL,
    VIDEOJUEGOS_ID NUMBER(5,0) NULL,
    ALBUM_MUSICAL_ID NUMBER(5,0) NULL,
    CONSTRAINT PRODUCTOS_ID_PK PRIMARY KEY (PRODUCTOS_ID),
    CONSTRAINT PELICULAS_ID_FK FOREIGN KEY (PELICULAS_ID),
    CONSTRAINT VIDEOJUEGOS_ID_FK FOREIGN KEY (VIDEOJUEGOS_ID),
    CONSTRAINT ALBUM_MUSICAL_ID FOREIGN KEY (ALBUM_MUSICAL_ID)
)
;

--
-- TABLA: PELICULAS
--
CREATE TABLE PELICULAS(
    PELICULAS_ID NUMBER(5,0) NOT NULL,
    CLASIFICACION VARCHAR2(3) NOT NULL,
    DURACION NUMBER(3,0) NOT NULL,
    GENERO VARCHAR2(10) NOT NULL,
    CONSTRAINT PELICULAS_ID_PK PRIMARY KEY (PELICULAS_ID),
    CONSTRAINT CLASIFICACION _CH CHECK (CLASIFICACION='A' OR CLASIFICACION='B' OR CLASIFICACION='B15' OR CLASIFICACION='C')
)
;

--
-- TABLA: VIDEOJUEGOS
--
CREATE TABLE VIDEOJUEGOS(
    VIDEOJUEGOS_ID NUMBER(5,0) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    DESCRIPCION VARCHAR2(40) NOT NULL,
    CONSOLA VARCHAR2(20) NOT NULL,
    CONSTRAINT PRODUCTOS_ID_PK PRIMARY KEY (PRODUCTOS_ID),
    CONSTRAINT NOMBRE_CH UNIQUE (NOMBRE),
    CONSTRAINT CONSOLA_CH CHECK (CONSOLA='PLAY STATION 4' OR CONSOLA='XBOX ONE' OR CONSOLA='NINTENDO SWITCH' OR CONSOLA='NINTENDO 3DS' OR CONSOLA='PC')
)
;

--
-- TABLA: ALBUM_MUSICAL
--
CREATE TABLE ALBUM_MUSICAL(
    ALBUM_MUSICAL_ID NUMBER(5,0) NOT NULL,
    CREADOR VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT ALBUM_MUSICAL_ID_PK PRIMARY KEY (ALBUM_MUSICAL_ID),
    CONSTRAINT NOMBRE_CH UNIQUE (NOMBRE)
)
;
